# Font, my favorite font is maple mono :)
font_family pixel code
font_size 18.0

# Make the cursor shape a beam
shell_integration no-cursor
cursor_shape beam
cursor #ff13ff
cursor_text_color #ff13ff

# Padding
window_padding_width 10
window_padding_height 10

# Scroll back up to 3000 lines.
scrollback_lines 3000

# Just a keybind to change font size to your liking, it's CTRL + scroll wheel up or down.
map ctrl+shift+plus change_font_size all +1.0
map ctrl+shift+minus change_font_size all -1.0

# Background opacity, set to 0 if you want blur/transparency.
# Blur works with hyprland, or sway-fx as a drop-in replacement for sway.
background_opacity 1


# Finally, the COLORS! these use the design system I made for this rice.
cursor               #ff13ff

selection_background #aa005d
selection_foreground #ff13ff

background           #33003e
foreground           #ff13ff

url_color            #78ff3e
underline_hyperlinks hover

#Black, There are 8 basic colors, each color has a dull and bright version, for the first 16 colors. You can set the remaining 240 colors as color16 to color255.
color0 #820055
color8 #ff00aa

#red
color1 #c70000
color9 #550000

#green
color2  #00ff00
color10 #528a26

#yellow
color3  #d60891
color11 #ff00ff

#blue
color4  #5500ff
color12 #300091

#orange
color5  #d95006
color13 #aa180b

#pink
color6  #ff0f77
color14 #a50a4d

#white
color7  #aa55ff
color15 #7038a8
